---
- hosts: all
  become: true
  gather_facts: true
  tasks:
   - name: install apache
     tags:
      - install
     yum:
      name: httpd
      state: installed
   - name: copy
     tags:
      - copying
     copy:
      src: index.html
      dest: /var/www/html/index.html
   - name: printing the message
     tags:
      - mssgg
      - printing msg
     debug:
      msg: "task is sucessfully installed" 
