---
- hosts: all
  gather_facts: true
  become: true
  tasks:
   - name: apache
     yum:
      name: httpd
      state: present
     when: ansible_os_family == "RedHat"

   - name: isntall apache
     apt:
      name: httpd
      state: present
     when: ansible_os_family == "ubuntu"
